name: Deploy To GitHub Pages

on:
  push:
    branches:
      - main  # Change to the branch you're deploying from

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main  # Change this to "main" if using main branch
          folder: .  # Make sure it deploys from the root directory
